//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgeDesingPattern.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisan
    {
        public Calisan()
        {
            this.CalisanIletisim = new HashSet<CalisanIletisim>();
            this.Ihale = new HashSet<Ihale>();
        }
    
        public int CalisanID { get; set; }
        public string KullaniciAd { get; set; }
        public string Sifre { get; set; }
        public int RolID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<bool> AktiflikDurumu { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual ICollection<CalisanIletisim> CalisanIletisim { get; set; }
        public virtual ICollection<Ihale> Ihale { get; set; }
    }
}
