//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgeDesingPattern.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriAramaKriter
    {
        public FavoriAramaKriter()
        {
            this.FavoriArama = new HashSet<FavoriArama>();
            this.FavoriOzellik = new HashSet<FavoriOzellik>();
        }
    
        public int FavoriAramaKriterID { get; set; }
        public Nullable<int> MarkaID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<System.DateTime> BaslangicYil { get; set; }
        public Nullable<System.DateTime> BitisYil { get; set; }
        public Nullable<decimal> BaslangicFiyat { get; set; }
        public Nullable<decimal> BitisFiyat { get; set; }
        public Nullable<int> BaslangicKM { get; set; }
        public Nullable<int> BitisKM { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ArabaModel ArabaModel { get; set; }
        public virtual ICollection<FavoriArama> FavoriArama { get; set; }
        public virtual Marka Marka { get; set; }
        public virtual ICollection<FavoriOzellik> FavoriOzellik { get; set; }
    }
}
