//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgeDesingPattern.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IhaleArac
    {
        public IhaleArac()
        {
            this.AracTeklif = new HashSet<AracTeklif>();
        }
    
        public int IhaleAracID { get; set; }
        public int IhaleID { get; set; }
        public int AracID { get; set; }
        public decimal IhaleBaslangicFiyat { get; set; }
        public decimal MinAlimFiyati { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual ICollection<AracTeklif> AracTeklif { get; set; }
        public virtual Ihale Ihale { get; set; }
    }
}
