//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgeDesingPattern.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciTip
    {
        public KullaniciTip()
        {
            this.Ihale = new HashSet<Ihale>();
            this.Kullanici = new HashSet<Kullanici>();
        }
    
        public int KullaniciTipID { get; set; }
        public string Tip { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<Ihale> Ihale { get; set; }
        public virtual ICollection<Kullanici> Kullanici { get; set; }
    }
}
