//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgeDesingPattern.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogID { get; set; }
        public System.DateTime LogTarih { get; set; }
        public string Kullanici { get; set; }
        public string Sayfa { get; set; }
        public string Islem { get; set; }
        public string LogMesaj { get; set; }
    }
}
